plugins {
    id "com.android.application"
}

def releaseKeystorePath = System.getenv("AUREA_KEYSTORE_PATH")

dependencies {
    implementation "androidx.core:core:1.15.0"
    implementation "net.java.dev.jna:jna:5.18.1@aar"
    implementation "com.alphacephei:vosk-android:0.3.75@aar"
}

android {
    namespace "it.creativemaker3d.aurea"
    compileSdk 35

    defaultConfig {
        applicationId "it.creativemaker3d.aurea"
        minSdk 26
        targetSdk 35
        versionCode 23
        versionName "0.2.12"
    }

    signingConfigs {
        release {
            if (releaseKeystorePath) {
                storeFile file(releaseKeystorePath)
                storePassword System.getenv("AUREA_KEYSTORE_PASSWORD")
                keyAlias System.getenv("AUREA_KEY_ALIAS")
                keyPassword System.getenv("AUREA_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            if (releaseKeystorePath) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
        }
    }
}
